// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hazcsjlqkhyvipkdzfvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhemNzamxxa2h5dmlwa2R6ZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODQ1NTIsImV4cCI6MjA3MjE2MDU1Mn0.12ljki5zuGdfWBfdTAQDlXENjMQyocATPK8owcaZJCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});